// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

use enum_iterator::Sequence;
use std::{result, str::FromStr};

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Sequence)]
pub(super) enum Keyword {
    Adj,
    Adjoint,
    AdjointUpper,
    And,
    Apply,
    As,
    Auto,
    BigInt,
    Body,
    Bool,
    Borrow,
    Controlled,
    ControlledUpper,
    Ctl,
    Distribute,
    Double,
    Elif,
    Else,
    Fail,
    False,
    Fixup,
    For,
    Function,
    If,
    In,
    Int,
    Internal,
    Intrinsic,
    Invert,
    Is,
    Let,
    Mutable,
    Namespace,
    Newtype,
    Not,
    One,
    Open,
    Operation,
    Or,
    Pauli,
    PauliI,
    PauliX,
    PauliY,
    PauliZ,
    Qubit,
    Range,
    Repeat,
    Result,
    Return,
    Slf,
    Set,
    String,
    True,
    Underscore,
    Unit,
    Until,
    Use,
    While,
    Within,
    Zero,
}

impl Keyword {
    pub(super) fn as_str(self) -> &'static str {
        match self {
            Self::Adj => "Adj",
            Self::Adjoint => "adjoint",
            Self::AdjointUpper => "Adjoint",
            Self::And => "and",
            Self::Apply => "apply",
            Self::As => "as",
            Self::Auto => "auto",
            Self::BigInt => "BigInt",
            Self::Body => "body",
            Self::Bool => "Bool",
            Self::Borrow => "borrow",
            Self::Controlled => "controlled",
            Self::ControlledUpper => "Controlled",
            Self::Ctl => "Ctl",
            Self::Distribute => "distribute",
            Self::Double => "Double",
            Self::Elif => "elif",
            Self::Else => "else",
            Self::Fail => "fail",
            Self::False => "false",
            Self::Fixup => "fixup",
            Self::For => "for",
            Self::Function => "function",
            Self::If => "if",
            Self::In => "in",
            Self::Int => "Int",
            Self::Internal => "internal",
            Self::Intrinsic => "intrinsic",
            Self::Invert => "invert",
            Self::Is => "is",
            Self::Let => "let",
            Self::Mutable => "mutable",
            Self::Namespace => "namespace",
            Self::Newtype => "newtype",
            Self::Not => "not",
            Self::One => "One",
            Self::Open => "open",
            Self::Operation => "operation",
            Self::Or => "or",
            Self::Pauli => "Pauli",
            Self::PauliI => "PauliI",
            Self::PauliX => "PauliX",
            Self::PauliY => "PauliY",
            Self::PauliZ => "PauliZ",
            Self::Qubit => "Qubit",
            Self::Range => "Range",
            Self::Repeat => "repeat",
            Self::Result => "Result",
            Self::Return => "return",
            Self::Slf => "self",
            Self::Set => "set",
            Self::String => "String",
            Self::True => "true",
            Self::Underscore => "_",
            Self::Unit => "Unit",
            Self::Until => "until",
            Self::Use => "use",
            Self::While => "while",
            Self::Within => "within",
            Self::Zero => "Zero",
        }
    }
}

impl FromStr for Keyword {
    type Err = ();

    fn from_str(s: &str) -> result::Result<Self, Self::Err> {
        enum_iterator::all::<Self>()
            .find(|kw| kw.as_str() == s)
            .ok_or(())
    }
}
