[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qdk"
version = "0.0.0"
description = "Microsoft Azure Quantum Development Kit Python package"
readme = "README.md"
authors = [ { name = "Microsoft" } ]
license = { file = "LICENSE.txt" }
requires-python = ">=3.9"
dependencies = [
  "qsharp==1.20.0",  # TODO: Should update to match 'qsharp' version on build
]

[project.optional-dependencies]
widgets = ["qsharp-widgets==1.20.0"]
azure = ["azure-quantum==3.2.0"]
qiskit = ["qiskit>=1.2.2,<2.0.0"]
jupyterlab = ["qsharp-jupyterlab==1.20.0"]
all = [
  "qsharp-widgets==1.20.0",
  "azure-quantum==3.2.0",
  "qiskit>=1.2.2,<2.0.0",
  "qsharp-jupyterlab==1.20.0",
]
