name: qsharp

trigger:
- main

pr:
- main

schedules:
- cron: "0 9 * * Sat"
  displayName: 'Build for Component Governance'
  branches:
    include:
    - main
  always: true

jobs:
- job: "qsharp-governance"
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 120
  steps:
  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component detection'

  - task: RustInstaller@1
    inputs:
      rustVersion: ms-$(RUST_TOOLCHAIN_VERSION)
      additionalTargets: wasm32-unknown-unknown
      cratesIoFeedOverride: $(cratesIoFeedOverride)
      toolchainFeed: $(toolchainFeed)
    displayName: Install Rust toolchain

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'

  - task: CodeQL3000Init@0
    displayName: CodeQL Initialize

  - script: |
      python ./prereqs.py --install
    displayName: Install Prereqs

  - script: |
      python build.py --no-check --no-test
    displayName: Build

  - script: |
      which ar
      which cc
      cc --version
    displayName: Display compile environment setup

  - script: |
      cd allocator/mimalloc-sys
      mkdir -p target/codeql/out/
      cc -O3 -ffunction-sections -fdata-sections -fPIC -gdwarf-2 -fno-omit-frame-pointer -I mimalloc/include -I mimalloc/src -Wall -Wextra -DMI_DEBUG=0 -o target/codeql/out/mimalloc-static.o -c mimalloc/src/static.c
      ar cq target/codeql/out/libmimalloc.a target/codeql/out/mimalloc-static.o
    displayName: Compile mimalloc for CodeQL

  - task: CodeQL3000Finalize@0
    displayName: CodeQL Finalize
