name: qsharp

trigger:
- main

pr:
- main

schedules:
- cron: "0 9 * * Sat"
  displayName: 'Build for Component Governance'
  branches:
    include:
    - main
  always: true

jobs:
- job: "qsharp"
  pool: 
    vmImage: 'ubuntu-latest'
  steps:
  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component detection'
